### ISSUE TITLE
Chirp-Snap Updates

### ISSUE THREAD

**Issue by tpalmatier** [goldstar611/chirp#3]
This snap updated on 02/10/23.  There have been updates since then but the snap is not updating

**Comment by goldstar611** [comment]
Hey Terry, I don't know exactly when snaps will update on users computers but you can always open up a terminal and run `snap refresh` to force an update of your installed snaps. 

There are two "channels" that can be chosen when you install from the snap store, `stable` vs `edge`. `edge` will always be more up to date than `stable` at the moment because I have to go into the snap interface and manually "promote" builds from edge to stable. I plan on writing a script to do this so I won't have to worry about it but I haven't got to it yet.

Let me know if the `snap refresh` command works for you.

Tony

**Comment by goldstar611** [comment]
Linking this here so I can refer back to it later: https://snapcraft.io/docs/release-management

**Comment by tpalmatier** [comment]
Thanks for the update Tony (no pun intended).

Using the snap refresh command in the CLI is how I always do it.  I guess I didn't know there was any other way to do it.

Your hard work it greatly appreciated.


Terry
AC8NR
________________________________

**Comment by goldstar611** [comment]
> Using the snap refresh command in the CLI is how I always do it.  I guess I didn't know there was any other way to do it.

Sounds like you're doing it the right way. How many versions behind is your installation of CHIRP?  

`snap refresh` should put you on either revision 518, 519 or 520 aka "snap-20230213+5ceff61d" depending on your CPU architecture. Those snap revisions correspond to tarballs for CHIRP-next-20230213

**Comment by tpalmatier** [comment]
It is up to date as of today.  Thanks.


Terry
AC8NR
________________________________
